## When a List is not the Answer

### Arrays
A Python array is as lean as C array.

In [1]:
# Example 2-20
from array import array
from random import random
floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.6840540276188549

In [2]:
with open('chapter2/floats.bin', 'wb') as fp:
    floats.tofile(fp)

In [3]:
floats2 = array('d')
with open('chapter2/floats.bin', 'rb') as fp:
    floats2.fromfile(fp, 10**7)

In [4]:
floats2[-1]

0.6840540276188549

In [6]:
floats2 == floats

True

### Memory Views

In [9]:
# Example 2-21: Changing the value of an array item by poking one of its bytes
numbers = array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [10]:
memv[0]

-2

In [11]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [12]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

### NumPy and SciPy

In [13]:
# Example 2-22: Basic operations with rows and columns in a numpy.ndarray
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
type(a)

numpy.ndarray

In [15]:
a.shape

(12,)

In [16]:
a.shape = 3, 4

In [17]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
a[:, 1]

array([1, 5, 9])

In [19]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Deques and Other Queues
The class collections.deque is a thread-safe double-ended queue designed for fast inserting and removing from both ends.

In [21]:
# Example 2-23
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [24]:
dq.appendleft(-1)
dq

deque([-1, -1, 7, 8, 9, 0, 1, 2, 3, 4])

In [25]:
dq.extend([11, 12, 33])
dq

deque([8, 9, 0, 1, 2, 3, 4, 11, 12, 33])

In [26]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 8, 9, 0, 1, 2, 3])